# Generated by Django 2.0.4 on 2018-11-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('sr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
