# Generated by Django 2.0.4 on 2018-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.TextField(default='Your answer'),
        ),
    ]
